export const arabicLocalization = {
  // =============== Main menu  ===============
  SIGN_IN: "تسجيل الدخول",
  SIGN_UP: "إنشاء حساب",
  FORGOT_PASSWORD: "استعادة كلمة المرور",
  RESET_PASSWORD: "تعيين كلمة مرور جديدة",
  VERIFY_YOUR_EMAIL: "تحقق من بريدك الإلكتروني",
  ACCEPT_INVITATION: "قبول الدعوة",

  // =============== Title and Sections  ===============
  ORGANIZATIONS: "المنظمات",
  MEMBERS: "الأعضاء",
  SECURITY: "الأمان",
  SETTINGS: "الإعدادات",
  SESSIONS: "الجلسات النشطة",
  API_KEYS: "مفاتيح الواجهة البرمجية",
  PASSKEYS: "مفاتيح المرور",
  PROVIDERS: "حسابات التواصل",
  PENDING_INVITATIONS: "الدعوات المعلقة",
  ACCOUNT: "الحساب",
  ORGANIZATION: "المنظمة",
  LOGO: "الشعار",
  AVATAR: "الصورة الشخصية",

  // =============== Forms and Inputs  ===============
  EMAIL: "البريد الإلكتروني",
  PASSWORD: "كلمة المرور",
  NEW_PASSWORD: "كلمة المرور الجديدة",
  CONFIRM_PASSWORD: "تأكيد كلمة المرور",
  CURRENT_PASSWORD: "كلمة المرور الحالية",
  NAME: "الاسم",
  USERNAME: "اسم المستخدم",
  ORGANIZATION_NAME: "اسم المنظمة",
  ORGANIZATION_SLUG: "رابط المنظمة",
  ROLE: "الدور",
  ONE_TIME_PASSWORD: "كلمة المرور لمرة واحدة",
  BACKUP_CODE: "كود الاستعادة",

  // =============== Buttons and Interactions  ===============
  SAVE: "حفظ",
  CANCEL: "إلغاء",
  CONTINUE: "متابعة",
  DELETE: "حذف",
  UPDATE_ROLE: "تحديث الدور",
  REMOVE_MEMBER: "إزالة عضو",
  LEAVE_ORGANIZATION: "مغادرة المنظمة",
  DELETE_ORGANIZATION: "حذف المنظمة",
  CREATE_ORGANIZATION: "إنشاء منظمة",
  MANAGE_ORGANIZATION: "إدارة المنظمة",
  INVITE_MEMBER: "دعوة عضو",
  SEND_INVITATION: "إرسال دعوة",
  ACCEPT: "قبول",
  REJECT: "رفض",
  UNLINK: "فك الارتباط",
  REVOKE: "سحب الصلاحية",
  UPLOAD: "رفع",
  UPLOAD_LOGO: "رفع شعار",
  UPLOAD_AVATAR: "رفع صورة شخصية",
  DELETE_LOGO: "حذف الشعار",
  DELETE_AVATAR: "حذف الصورة الشخصية",
  CREATE_API_KEY: "إنشاء مفتاح واجهة",
  ADD_PASSKEY: "إضافة مفتاح مرور",
  ENABLE_TWO_FACTOR: "تفعيل المصادقة الثنائية",
  DISABLE_TWO_FACTOR: "تعطيل المصادقة الثنائية",

  // ===============  Messages and Directives  ===============
  REMEMBER_ME: "تذكرني",
  DONT_HAVE_AN_ACCOUNT: "ليس لديك حساب؟",
  ALREADY_HAVE_AN_ACCOUNT: "لديك حساب بالفعل؟",
  FORGOT_PASSWORD_LINK: "نسيت كلمة المرور؟",
  FORGOT_AUTHENTICATOR: "نسيت المصادقة؟",
  OR_CONTINUE_WITH: "أو متابعة عبر",
  BY_CONTINUING_YOU_AGREE: "باستمرارك، أنت توافق على",
  TERMS_OF_SERVICE: "شروط الخدمة",
  PRIVACY_POLICY: "سياسة الخصوصية",
  PROTECTED_BY_RECAPTCHA: "هذا الموقع محمي بواسطة reCAPTCHA",
  CHANGE_PASSWORD: "تغيير كلمة المرور",
  CHANGE_PASSWORD_INSTRUCTIONS: "أدخل كلمة المرور الحالية وكلمة مرور جديدة.",
  PASSWORD_PLACEHOLDER: "********",
  PASSWORD_TOO_LONG: "كلمة المرور طويلة جدًا.",
  PASSWORD_TOO_SHORT: "كلمة المرور قصيرة جدًا.",
  SET_PASSWORD: "تعيين كلمة المرور",
  NEW_PASSWORD_REQUIRED: "كلمة المرور الجديدة مطلوبة.",
  NEW_PASSWORD_PLACEHOLDER: "كلمة المرور الجديدة",
  CURRENT_PASSWORD_PLACEHOLDER: "كلمة المرور الحالية",
  CONFIRM_PASSWORD_PLACEHOLDER: "تأكيد كلمة المرور",
  INVALID_PASSWORD: "كلمة المرور غير صحيحة.",
  FORGOT_PASSWORD_DESCRIPTION:
    "نسيت كلمة المرور؟ يمكنك استعادتها عبر البريد الإلكتروني.",
  FORGOT_PASSWORD_EMAIL: "البريد الإلكتروني لاستعادة كلمة المرور",
  USER_ALREADY_HAS_PASSWORD: "هذا المستخدم لديه كلمة مرور بالفعل.",
  INVALID_EMAIL_OR_PASSWORD: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
  INVALID_PHONE_NUMBER_OR_PASSWORD: "رقم الهاتف أو كلمة المرور غير صحيحة.",
  CONFIRM_PASSWORD_REQUIRED: "تأكيد كلمة المرور مطلوب.",
  RESET_PASSWORD_ACTION: "إعادة تعيين كلمة المرور",
  PASSWORD_COMPROMISED:
    "تم اكتشاف أن هذه الكلمة مخترقة، يرجى اختيار كلمة مرور أخرى.",
  FORGOT_PASSWORD_ACTION: "استعادة كلمة المرور",

  // =============== Status Messages  ===============
  UPDATED_SUCCESSFULLY: "تم تحديثه بنجاح",
  COPIED_TO_CLIPBOARD: "تم النسخ إلى الحافظة",
  INVITATION_ACCEPTED: "تم قبول الدعوة بنجاح",
  INVITATION_REJECTED: "تم رفض الدعوة بنجاح",
  MEMBER_ROLE_UPDATED: "تم تحديث دور العضو بنجاح",
  REMOVE_MEMBER_SUCCESS: "تم إزالة العضو بنجاح",
  LEAVE_ORGANIZATION_SUCCESS: "تم مغادرة المنظمة بنجاح",
  DELETE_ORGANIZATION_SUCCESS: "تم حذف المنظمة بنجاح",
  CREATE_ORGANIZATION_SUCCESS: "تم إنشاء المنظمة بنجاح",
  SEND_INVITATION_SUCCESS: "تم إرسال الدعوة بنجاح",
  RESET_PASSWORD_SUCCESS: "تم تعيين كلمة المرور بنجاح",
  CHANGE_PASSWORD_SUCCESS: "تم تغيير كلمة المرور بنجاح",
  TWO_FACTOR_ENABLED: "تم تفعيل المصادقة الثنائية",
  TWO_FACTOR_DISABLED: "تم تعطيل المصادقة الثنائية",

  // =============== Erorrs Messages  ===============
  EMAIL_REQUIRED: "البريد الإلكتروني مطلوب",
  PASSWORD_REQUIRED: "كلمة المرور مطلوبة",
  PASSWORDS_DO_NOT_MATCH: "كلمتا المرور غير متطابقتين",
  INVALID_EMAIL: "بريد إلكتروني غير صحيح",
  USER_NOT_FOUND: "المستخدم غير موجود",
  TOO_MANY_ATTEMPTS: "محاولات كثيرة، حاول لاحقاً",
  INVALID_CODE: "كود غير صحيح",
  SESSION_EXPIRED: "انتهت صلاحية الجلسة",
  ORGANIZATION_ALREADY_EXISTS: "المنظمة موجودة مسبقاً",
  INVITATION_EXPIRED: "انتهت صلاحية الدعوة",
  SLUG_REQUIRED: "رابط المنظمة مطلوب",
  UNKNOWN_ERROR: "خطأ غير متوقع",
  INVALID_USERNAME_OR_PASSWORD: "اسم المستخدم أو كلمة المرور غير صحيحة",

  // =============== Recommendations and instructions  ===============
  LOGO_DESCRIPTION: "انقر على الشعار لرفع صورة مخصصة من ملفاتك",
  LOGO_INSTRUCTIONS: "الشعار اختياري لكنه موصى به بشدة",
  AVATAR_DESCRIPTION: "انقر على الصورة لرفع صورة شخصية من ملفاتك",
  AVATAR_INSTRUCTIONS: "الصورة الشخصية اختيارية لكنها موصى بها بشدة",
  DELETE_ORGANIZATION_DESCRIPTION:
    "إزالة دائمة للمنظمة ومحتوياتها. لا يمكن التراجع عن هذا الإجراء.",
  ACCEPT_INVITATION_DESCRIPTION: "لقد تمت دعوتك للانضمام إلى منظمة",
  MEMBERS_DESCRIPTION: "إضافة أعضاء جدد وإدارة أدوارهم",
  INVITE_MEMBER_DESCRIPTION: "إرسال دعوة لإضافة عضو جديد لمنظمتك",
  UPDATE_ROLE_DESCRIPTION: "تحديث دور هذا العضو",
  BACKUP_CODES_DESCRIPTION:
    "احفظ هذه الأكواد في مكان آمن. تستخدمها لاسترداد حسابك إذا فقدت وسيلة المصادقة الثنائية",
  TWO_FACTOR_CARD_DESCRIPTION: "أضف طبقة أمان إضافية لحسابك",
  ORGANIZATIONS_DESCRIPTION: "إدارة منظماتك وعضوياتك",
  ORGANIZATION_NAME_DESCRIPTION: "هذا هو الاسم الظاهر لمنظمتك",
  ORGANIZATION_SLUG_DESCRIPTION: "هذا هو رابط النطاق الخاص بمنظمتك",
  VERIFY_YOUR_EMAIL_DESCRIPTION:
    "يرجى التحقق من عنوان بريدك الإلكتروني. افحص صندوق الوارد لرسالة التحقق.",
  NAME_DESCRIPTION: "يرجى إدخال اسمك الكامل.",
  EMAIL_DESCRIPTION: "أدخل بريدك الإلكتروني لتسجيل الدخول أو إنشاء حساب.",
  SIGN_IN_DESCRIPTION: "تسجيل الدخول إلى حسابك.",
  SIGN_UP_DESCRIPTION: "إنشاء حساب جديد.",
  ACCOUNTS_DESCRIPTION: "إدارة الحسابات المرتبطة.",
  SESSIONS_DESCRIPTION: "جلسات تسجيل الدخول النشطة.",
  SET_PASSWORD_DESCRIPTION: "تعيين كلمة مرور جديدة لحسابك.",
  USERNAME_DESCRIPTION: "اسم المستخدم الخاص بك.",
  RESET_PASSWORD_DESCRIPTION: "إعادة تعيين كلمة المرور.",
  CHANGE_PASSWORD_DESCRIPTION: "تغيير كلمة المرور الحالية.",

  // =========================================================================

  EMAIL_VERIFY_CHANGE:
    "تم تغيير البريد الإلكتروني. يرجى التحقق من البريد الجديد.",

  EMAIL_CAN_NOT_BE_UPDATED: "لا يمكن تحديث البريد الإلكتروني.",
  EMAIL_IS_THE_SAME: "البريد الإلكتروني المدخل هو نفسه الحالي.",
  EMAIL_INSTRUCTIONS: "سوف نرسل لك رمز تحقق عبر البريد الإلكتروني.",
  EMAIL_NOT_VERIFIED: "البريد الإلكتروني غير مُحقق.",
  EMAIL_OTP: "رمز التحقق عبر البريد الإلكتروني",
  EMAIL_OTP_DESCRIPTION: "يرجى إدخال رمز التحقق المرسل إلى بريدك.",
  EMAIL_PLACEHOLDER: "example@example.com",
  EMAIL_VERIFICATION: "التحقق من البريد الإلكتروني",
  EMAIL_OTP_SEND_ACTION: "إرسال رمز التحقق",
  SIGN_UP_EMAIL: "تسجيل بحساب بريد إلكتروني",
  EMAIL_OTP_VERIFICATION_SENT: "تم إرسال رمز التحقق إلى بريدك الإلكتروني.",
  EMAIL_OTP_VERIFY_ACTION: "تحقق الآن",
  EMAIL_VERIFICATION_REQUIRED: "التحقق من البريد الإلكتروني مطلوب.",
  USER_EMAIL_NOT_FOUND: "البريد الإلكتروني غير مسجل لدينا.",

  NAME_INSTRUCTIONS: "أدخل اسمك الكامل كما تريد أن يظهر في حسابك.",
  NAME_PLACEHOLDER: "الاسم الكامل",
  INVALID_NAME_LENGTH: "الاسم يجب أن يكون بين 2 و 50 حرفًا.",

  UNAUTHORIZED_SESSION: "ليس لديك صلاحية للوصول إلى هذه الجلسة.",
  INVALID_SESSION_TOKEN: "رمز الجلسة غير صالح.",
  FAILED_TO_GET_SESSION: "فشل في جلب بيانات الجلسة.",
  COULD_NOT_CREATE_SESSION: "تعذر إنشاء جلسة جديدة.",
  FAILED_TO_CREATE_SESSION: "فشل في إنشاء الجلسة.",
  UNABLE_TO_CREATE_SESSION: "غير قادر على إنشاء الجلسة.",
  SIGN_IN_USERNAME_DESCRIPTION: "أدخل اسم المستخدم لتسجيل الدخول.",

  API_KEYS_DESCRIPTION: "إدارة مفاتيح API الخاصة بك للوصول إلى خدمات التطبيق.",
  DELETE_ACCOUNT_SUCCESS: "تم حذف الحساب بنجاح.",
  PASSKEYS_DESCRIPTION: "إدارة مفاتيح المرور المرتبطة بحسابك.",
  PROVIDERS_DESCRIPTION: "عرض وإدارة مزودي تسجيل الدخول المرتبطين.",
  DISABLED_CREDENTIALS_DESCRIPTION: "بيانات الاعتماد التي تم تعطيلها حاليًا.",
  DELETE_ACCOUNT_INSTRUCTIONS:
    "هل أنت متأكد أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.",

  SIGN_IN_ACTION: "تسجيل الدخول",
  SIGN_IN_USERNAME_PLACEHOLDER: "اسم المستخدم",
  SIGN_IN_WITH: "تسجيل الدخول باستخدام",
  SIGN_OUT: "تسجيل الخروج",
  SIGN_UP_ACTION: "إنشاء حساب جديد",
  ANONYMOUS_USERS_CANNOT_SIGN_IN_AGAIN_ANONYMOUSLY:
    "لا يمكن للمستخدمين المجهولين تسجيل الدخول مرة أخرى كمجهولين.",

  UNEXPECTED_ERROR: "حدث خطأ غير متوقع. يرجى المحاولة لاحقًا.",
  CONTINUE_WITH_AUTHENTICATOR: "المتابعة باستخدام تطبيق المصادقة",
  SEND_VERIFICATION_CODE: "إرسال رمز التحقق",

  INVALID_USER_ID_FROM_API_KEY: "معرف المستخدم المستخرج من مفتاح API غير صالح.",
  INVALID_OTP: "رمز التحقق غير صحيح.",
  INVALID_PHONE_NUMBER: "رقم الهاتف غير صحيح.",
  INVALID_TOKEN: "الرمز غير صالح أو منتهي.",
  INVALID_USERNAME: "اسم المستخدم غير صحيح.",
  INVALID_REMAINING: "القيمة المتبقية غير صالحة.",
  IS_INVALID: "غير صالح.",
  IS_THE_SAME: "المدخل هو نفسه الحالي.",
  KEY_DISABLED: "تم تعطيل المفتاح.",
  KEY_DISABLED_EXPIRATION:
    "تم تعطيل هذا المفتاح وسيتم حذفه تلقائيًا بعد انتهاء صلاحيته.",
  METADATA_DISABLED: "تم تعطيل الوصول إلى البيانات الوصفية.",

  // =============== Roles and Powers  ===============
  OWNER: "مالك",
  ADMIN: "مدير",
  MEMBER: "عضو",
  GUEST: "ضيف",

  // =============== Confirmation Messages  ===============
  REMOVE_MEMBER_CONFIRM: "هل أنت متأكد من رغبتك في إزالة هذا العضو من المنظمة؟",
  LEAVE_ORGANIZATION_CONFIRM: "هل أنت متأكد من رغبتك في مغادرة هذه المنظمة؟",
  DELETE_ACCOUNT_DESCRIPTION:
    "إزالة دائمة لحسابك ومحتوياته. لا يمكن التراجع عن هذا الإجراء.",
  DELETE_API_KEY_CONFIRM: "هل أنت متأكد من رغبتك في حذف مفتاح الواجهة هذا؟",

  // =============== Technical Terms  ===============
  API_KEY: "مفتاح واجهة برمجية (API)",
  MAGIC_LINK: "رابط الدخول السحري",
  SELECT_ROLE: "اختر دوراً",
  NO_EXPIRATION: "بدون انتهاء",
  EXPIRES: "ينتهي في",
  NEVER_EXPIRES: "لا ينتهي أبداً",
  PERSONAL_ACCOUNT: "حساب شخصي",
  CURRENT_SESSION: "الجلسة الحالية",
  TRUST_DEVICE: "الثقة بهذا الجهاز",

  // =============== Messages for organizations  ===============
  DELETE_ORGANIZATION_INSTRUCTIONS: "أدخل رابط المنظمة للمتابعة:",
  SLUG_DOES_NOT_MATCH: "رابط المنظمة غير متطابق",

  // =============== Other Messages  ===============
  SWITCH_ACCOUNT: "تبديل الحساب",
  RESEND_VERIFICATION_EMAIL: "إعادة إرسال بريد التحقق",
  GO_BACK: "العودة",
  SESSION_NOT_FRESH: "جلسة غير نشطة، يرجى تسجيل الدخول مرة أخرى",
};
